### ISSUE TITLE
PHPUnit tests failing with PDT 8

### ISSUE THREAD

**Issue by bighead85** [eclipse/pdt#154]
Hi All,
Windows 11 22H2
PHP 8.2.5
PHPUnit 10.1
Eclipse Version: 2023-03 (4.27.0) Build id: 20230309-1520

Running PDT 8 on my Eclipse with latest updates;
Eclipse PDT	PHPUnit Plug-in	8.0.0.202305142018	org.eclipse.php.phpunit.feature

With PHPUnit from composer, I get an error on run of PHPUnit however in my Windows 11 environment I can run directly from powershell/command prompt without issue.
From in eclipse I get console output and then error; 

> PHPUnit 10.1.3 by Sebastian Bergmann and contributors.
> Unknown option "--printer"
![image](https://github.com/eclipse/pdt/assets/6860758/d937ac74-40b9-47ce-9b04-e48f1fc12e5b)

When I went back to PHPUnit 9 i get slightly different console but same PHPUnit error. 

> PHP Deprecated:  Creation of dynamic property PHPUnitEclipseLogger::$out is deprecated in C:\Users\%USER%\AppData\Local\Temp\phpunit_printer\PHPUnitLogger.php on line 603
> 
> Deprecated: Creation of dynamic property PHPUnitEclipseLogger::$out is deprecated in C:\Users\%USER%\AppData\Local\Temp\phpunit_printer\PHPUnitLogger.php on line 603
> PHPUnit 9.6.8 by Sebastian Bergmann and contributors.

Has any one experienced similar and able to resolve, could well be issue on my local environment but when compared with others on PDT 7.2 we cannot find any differences only my PDT version.

**Comment by zulus** [comment]
Looks like you run on PHP8.* which deprecated dynamic props. For now I fixed compatibility with PHP8, should work fine with upcoming build

PHPUnit 10 removes printers, so we have to reimplement our logger via events, see sebastianbergmann/phpunit#4807

**Comment by bighead85** [comment]
@zulus  thank you. I confirm with latest I no longer get the Deprecated messages when using PHPUnit 9.6.8.
I do still get the other main error though when trying to run my tests, this now persists in PHPUnit 9 and 10 with PDT8.
![image](https://github.com/eclipse/pdt/assets/6860758/6dd49e84-f09c-4ceb-9470-52aadd8075cf)

**Comment by bighead85** [comment]
@zulus I did the change as you commited and now PHPUnit is running for me. Thank you very much for speed of your responses.
